[package]
name = "proboscis-postgres-protocol"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
bytes = "1"
thiserror = "1"
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.50"

[dev-dependencies]
tokio-test = "*"