[package]
name = "proboscis"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.4.2"
bytes = "1"
postgres = { version = "0.19", optional = true }
md-5 = "0.9.1"

[features]
e2e = ["postgres"]

[[bin]]
bench = false
path = "src/bin.rs"
name = "proboscis"
