max_pool_size = 10
k = 3
connection_uri = "postgresql://postgres:postgres@localhost:5432/postgres"

# [tls]
# pcks_path = "./examples/openssl/identity.p12"
# password = "password"

[listener]
host = "0.0.0.0"
port = "6432"

[[credentials]]
username = "admin"
password = "password"

[[columns]]
type = "identifier"
name = "contacts.first_name"

[[columns]]
type = "identifier"
name = "contacts.last_name"

[[columns]]
type = "pseudo_identifier"
name = "contacts.age"
