[package]
name = "postgres-protocol"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
byteorder = "1.4.2"
bytes = "1"
omnom = "3.0.0"
tokio = { version = "1.4.0", features = ["full"] }
