[package]
name = "proboscis-resolver-transformer"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1"
arrow = "5.5.0"
async-trait = "0.1.50"
sqlparser = "0.9.0"
tracing = "0.1"
lazy_static = "1.4.0"

proboscis-core = { version = "0.1.0", path = "../proboscis-core" }
